description: |
  "The official Go Docker image on Docker Hub.
  Found here: https://hub.docker.com/_/golang"
parameters:
  tag:
    description: "The `golang` Docker image version tag."
    type: string
    default: "1.24-alpine"
docker:
  - image: golang:<< parameters.tag >>
